### ISSUE TITLE
Permissions error following the guide

### ISSUE THREAD

**Issue by poltak** [dylanlindgren/docker-laravel-nginx#8]
I've followed the blog post you wrote exactly, using the `docker-laravel-composer` to create a new laravel project, using the same command in the blog post, however after all the containers have been run I cannot get the page to load. I am getting permissions errors in my nginx log in `myapp/www/logs/error.log`. My page accesses are being logged correctly in `access.log`.

Here is the message I'm getting:

```
PHP message: PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream o$
 file "/data/www/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied
' in /data/www/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:97
Stack trace:
#0 /data/www/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handl
er\StreamHandler->write(Array)
#1 /data/www/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandl
er->handle(Array)
#2 /data/www/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, Object(S
ymfony\Component\Debug\Exception\FatalErrorException), Array)
#3 /data/www/vendor/laravel/framework/src/Illuminate/Log/Writer.php(202): Monolog\Logger->error(Object(S
ymfony\Component\Debug\Exception\FatalErrorException), Array)
#4 /data/www/vendor/laravel/framework/src/Illuminate/Log/Writer.php(113)
```

I've tried changing the ownership on the `myapp/www` directory as a whole, but still no progress.

I am running on a Linux host, but also tried on my local OS X macbook using boot2docker, or whatever they call it now. Same thing on both.

Did you ever run into this issue?

**Comment by GAN-ofm** [comment]
I had the same.
change the permissions from the directories 'storage' and 'bootstrap'
